---
title: ''
author: "Anton Sobolev"
email: anton.sobolev@yale.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  word_document: default
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=.75in
jobtitle: Postdoctoral associate in the Leitner Program on Political Economy at Yale University
keywords: R Markdown, academic CV, template
linkcolor: Brown
fontawesome: yes
address: Department of Political Science - Yale University - 115 Prospect Street, New Haven, CT 06520
updated: no
urlcolor: Brown
web: www.asobolev.com
xcolor: yes
---

# TEACHING PORTFOLIO

**Yale University**, ***Department of Political Science***

\hskip 1cm Big Data, AI, and Russian Politics (2020)

**University of California, Los Angeles**, ***Anderson School of Business***

\hskip 1cm Technology Analytics (MBA), with Prof. Keith Chen (2018)

\hskip 1cm Competitive Analytics (MSBA), with Prof. Keith Chen (2018)

**University of California, Los Angeles**, ***Department of Political Science***

\hskip 1cm Politics and Government of Post-Communist Russia, with Prof. Daniel Treisman (2014-17)

\hskip 1cm Diversity, Disagreement, and Democracy, with Prof. Susanne Lohmann (2016)

\hskip 1cm Data Analysis, with Prof. Erin Hartman (2018)

\hskip 1cm Politics and Strategy, with Prof. Michael Chwe (2017)

**Higher School of Economics, Moscow**, ***Department of Political Science***

\hskip 1cm Models of Risk in Politics and Economics (MA, 2012-13)

\hskip 1cm Political Theory (2011-13)

