---
title: ''
author: "Anton Sobolev"
email: anton.sobolev@yale.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  word_document: default
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=.75in
jobtitle: Postdoctoral associate in the Leitner Program on Political Economy at Yale University
keywords: R Markdown, academic CV, template
linkcolor: Brown
fontawesome: yes
address: Department of Political Science - Yale University - 115 Prospect Street, New Haven, CT 06520
updated: no
urlcolor: Brown
web: www.asobolev.com
xcolor: yes
---

# REFERENCES

Prof. Daniel Treisman (chair of the Ph.D. dissertation committee), Department of Political Science, UCLA, 4289 Bunche Hall, Los Angeles, CA 90095, [treisman@polisci.ucla.edu](treisman@polisci.ucla.edu) 

*Interfolio automatic reference request*: [send.2020.68DD2BF264@interfolio.com](send.2020.68DD2BF264@interfolio.com)

Prof. Chad Hazlett (chair of the M.Sc. dissertation committee), Department of Statistics, UCLA, 8105G Mathematical Sciences, Los Angeles, CA 90095, [chazlett@ucla.edu](chazlett@ucla.edu)

*Interfolio automatic reference request*: [send.2020.15ACE018AE@interfolio.com](send.2020.15ACE018AE@interfolio.com)

Prof. Konstantin Sonin (chair of the M.A. dissertation committee), Harris Public Policy School, University of Chicago, 1155 E60 St, Chicago, IL 60637, [ksonin@uchicago.edu](ksonin@uchicago.edu)

*Interfolio automatic reference request*: [send.2020.4D5126918F@interfolio.com](send.2020.4D5126918F@interfolio.com)


