---
title: ''
author: "Evgenia Gorina"
email: egorina@utdallas.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  word_document: default
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=.75in
jobtitle: Associate Professor, School of Economic, Political and Policy Sciences
keywords: R Markdown, academic CV, template
linkcolor: Brown
fontawesome: yes
address:  Cecil H. Green Hall | 800 West Campbell Road, GR 3.202 | Richardson, TX 75080-3021
phone: 972-883-3515
updated: no
urlcolor: Brown
web: www.evgorina.com
xcolor: yes
---

# ACADEMIC POSITIONS
**Associate Professor** in Public and Nonprofit Management, School of Economic, \hfill 2020-    
  Political and Policy Sciences, University of Texas at Dallas   

**Assistant Professor**, School of Economic, Political and Policy Sciences, \hfill 2013-20  
  Political and Policy Sciences, University of Texas at Dallas 

# EDUCATION
**Arizona State University**, Ph.D. in Public Administration and Policy  \hfill 2013

**Dobrolyubov State Linguistic University** (Nizhny Novgorod), M.A. in Foreign \hfill 2005  
  Language Translation (English & French)  

# RESEARCH
## Research Areas
government financial management, municipal financial condition, form of government, public sector retirement systems, migration

## Articles

[**"Voters, Neighbors, and City Performance in Sustainability Transitions"**](#forthcoming) in *Public Integrity*, 2020, 114(4): 1343-1351 (with Doug Goodman, Romeo Abraham, Brett Cease, and Edward French)

[**"Pension Reforms and Public Sector Turnover"**](https://academic.oup.com/jpart/advance-article-abstract/doi/10.1093/jopart/muz009/5522313?redirectedFrom=fulltext) in *Journal of Public Administration Research and Theory*, 2020, 30(1), 96-112 (with Trang Hoang)

[**"Toward a Theory of Fiscal Slack"**](https://doi.org/10.1111/pbaf.12240) in *Public Budgeting and Finance*, 2020, 39(4): 48-74 (with Maher Craig and Sungho Park)

[**"Belonging and Political Participation: Evidence from a Presidential Election in Kyrgyzstan"**](https://doi.org/10.1080/09668136.2019.1665168) in *Europe-Asia Studies*, 2019, 71(9), 1562-83 (with Victor Agadjanian)

[**"Economic Swings, Political Instability and Migration in Kyrgyzstan"**](https://doi.org/10.1080/09668136.2019.1665168) in *European Journal of Population*, 2019, 71(9): 1562-83 (with Victor Agadjania)

[**"City Revenue Structure and Unfunded Pension Liabilities"**](https://doi.org/10.1177/0160323X18817806) in *State and Local Government Review*, 2018, 50(3): 189-202

[**"Fiscal Effects of Municipal Annexation: Evidence from a Large National Sample of Urban Municipalities"**](https://doi.org/10.1111/grow.12260) in *Growth and Change*, 2018, 49(4): 612-635 (with Wang Jing)

[**"Migrant Women's Economic Success in Russia: Objective Reality and Subjective Assessment"**](https://doi.org/10.1080/1369183X.2017.1333410) in *Journal of Ethnic and Migration Studies*, 2018, 44(9): 1584-1603 (with Victor Agadjanian and Natalya Zotova)

[**"Local Fiscal Distress: Measurement and Prediction"**](https://doi.org/10.1111/pbaf.12165) in *Public Budgeting and Finance*, 2018, 38(1): 72-94 (with Craig Maher and Marc Joffe)

[**"Emergency Financial Management in Small Michigan Cities: Short-term Fix or Fiscal Sustainability"**](https://www.jstor.org/stable/26383395) in *Public Administration Quarterly*, 2017, 41(3): 532-568 (with Anna Clark)

[**"Economic Incorporation, Civic Inclusion, and Social Ties: Plans to Return Home among Central Asian Female Migrants in Moscow, Russia"**](https://doi.org/10.1111/imre.12117) in *International Migration Review*, 2014, 48(3): 577-603 (with Victor Agadjanian and Cecilia Menjivar)

[**"Effects of the Form of Government and Property Tax Limits on Local Finance in the Context of Revenue and Expenditure Simultaneity"**](https://doi.org/10.1111/j.1540-5850.2012.01022.x) in *Public Budgeting and Finance*, 2012, 32(4): 19-45 (with Jeffrey Chapman)

[**"Municipal Fiscal Stress and the Use of Tax Increment Financing (TIF)"**](https://www.jstor.org/stable/41349091) in *Town Planning Review*, 2012, 83(2): 195-203 (with Jeffrey Chapman)

## Book Chapters

[**"Other People’s Money: Financing Public Goods in Texas"**](#link) in *Texas Yesterday and Today: Readings in Texas Politics and Public Policy*, 2017, Great River Learning

## Work In Progress

[**"Effects of a Mandatory Defined Contribution Plan on Teacher Exits from the K-12 System in Alaska"**](#InProgress) (with Jen Sidorova, Mark Joffe, Anil Niraula)

[**"How Well Can We Predict Municipal Financial Emergencies with Prior Year Financial Ratios and Local Economic Indicators?"**](#InProgress) (with Marc Joffe and Craig Maher)

[**"Form of Government and Responses to a Fiscal Shock"**](#InProgress)

[**"Pension Plan Governance and Asset Allocation"**](#InProgress) (with Kenneth Kriz)

[**"Costs of Information Asymmetry in Debt Issuance"**](#InProgress) (with Trang Hoang and Jing Wang)

[**"Immigration and Public Finance Locally"**](#InProgress) (with Youngrok Kim)

[**"Changes in the Internal and International Migration Intentions in Kyrgyzstan over 2011 and 2017"**](#InProgress) (with Victor Agadjanian)

[**"Social Security Coverage and Teacher Mobility in Texas"**](#InProgress) (with Dongwoo Kim and James Harrington)

## Commentaries, Op-eds, Working Papers

[**"When cities face hard fiscal times, pension promises are the first to go underfunded"**](https://blogs.lse.ac.uk/usappblog/2019/06/14/when-cities-face-hard-financial-times-pension-liabilities-are-often-the-first-to-go-underfunded/), London School of Economics Blog on American Politics and Policy, June 2019

[**"Using Fiscal Ratios to Predict Financial Emergencies"**](https://www.mercatus.org/publications/fiscal-ratios-predict-local-fiscal-distress), Mercatus Working Paper, April 2018 (with Marc Joffe and Craig Maher)

[**"Environmental Sustainability Adoption and Financial Management in U.S. Cities"**](#oped), *Climate Change and Public Administration Symposium at Public Administration Review*, July 2017 (with Brett Cease, Doug Goodman, and Romeo Abraham)

[**"Is There a Way to Predict Local Fiscal Struggles?"**](https://www.usnews.com/opinion/economic-intelligence/articles/2017-01-03/how-cities-get-into-fiscal-trouble), *U.S. News and World Report*, January 2017 (with Craig Maher)

[**"Measuring and Modeling Determinants of Fiscal Stress in US Municipalities"**](https://www.mercatus.org/publications/measuring-modeling-determinants-fiscal-stress-municipalities), *Mercatus Working Paper*, November 2016 (with Craig Maher)

# SELECTED PRESENTATIONS

ASA (2017, 2014, 2013), WPSA (2022), WSSA (2019, 2018, 2014, 2012, 2010), Association for Budgeting and Financial Management (2021, 2018, 2017, 2016, 2015, 2014, 2013), Association for Policy Analysis and Management (2020, 2015), Association for Education Finance and Policy (2020), Association for Budgeting and Financial Management (2019, 2014), National Tax Association (2017, 2016, 2015, 2014), American Society for Public Administration (2016), Association for Public Policy and Management (2015, 2013), International Population Conference (Busan, Korea, 2013), Population Association of America (2014, 2013)

# FUNDED PROJECTS

**Social Security Coverage and Texas Teacher Labor Market Outcomes** \hfill 2021    
  UT Dallas Office of Research Seed Grant (8,000$)  

**Can Fiscal Ratios Predict Government Financial Crises?** \hfill 2017    
  Mercatus Center, George Mason University (12,400$)  
  
**Modelling Fiscal Stress in U.S. Municipalities** \hfill 2016    
  Gil Crain Grant of Government Accounting Standards Board (5,000$)  
  
**Municipal Fiscal Distress: Measurement and Prediction** \hfill 2015    
  Mercatus Center, George Mason University (8,000$)

# AWARDS AND DISTINCTIONS

**Distinguished Graduate Instruction Award**, UT Dallas,  \hfill 2021  
  School of Economic, Political and Policy Sciences 

**President’s Teaching Award for Graduate Instruction** (Nominee), UT Dallas \hfill 2021  

**President’s Teaching Award for Undergraduate Instruction** (Nominee), UT Dallas \hfill 2021  

**President’s Teaching Award for Undergraduate Instruction** (Nominee), UT Dallas \hfill 2020  

**Outstanding Graduate Professor**, UT Dallas, Program in Public and Nonprofit Management  \hfill 2018  

**Outstanding Doctoral Paper Award** (Finalist), ASU \hfill 2012

**Price Waterhouse Coopers Tax and Accounting Extreme Challenge**, ASU \hfill 2010

**Frank and June Sackton Doctoral Research Scholarship**, ASU \hfill 2010 

**Doctoral Program Enrollment Scholarship**, ASU \hfill 2007  

# TEACHING

**UT Dallas**, ***School of Economic, Political and Policy Sciences***

\hskip 1cm PPPE 6342: Research Design II (2022, PhD)

\hskip 1cm PA 3378: Public Finance and Economics (2022, 2021, 2020, 2019, 2018, 2016, 2015, 2014, BA)

\hskip 1cm PA 7306: Foundations of Public Affairs (2021, 2020, 2019, 2017, 2016, 2015, PhD)

\hskip 1cm EPPS 6313: Introduction to Quantitative Methods (2021, 2020, 2018, 2017, 2016, 2015, MA)

\hskip 1cm PA 7360: Advanced Fiscal and Budgetary Policy (2021, 2019, 2016, 2014, 2013, PhD)

\hskip 1cm PA 6374: Financial Management for Nonprofit Organizations (2020, 2018, 2017, 2015, MA)

\hskip 1cm EPPS 6113: Introduction to Quantitative Methods (2019, MA)

\hskip 1cm EPPS 2302: Methods of Quantitative Analysis in Social and Policy Sciences (2018, BA)

\hskip 1cm PA 7317: Microeconomics and Public Policy (2014, MA/PhD)

**Arizona State University**, ***School of Public Affairs***

\hskip 1cm PAF 201: Economics & Public Policy (2012, 2011, 2010, BA)

\hskip 1cm PAF 549: Diversity Issues & Public Policy (2012, 2011, 2010, MA)

\hskip 1cm PAF 504: Public Affairs Economics (2012, 2011, 2010, MA)

<!-- 
# REFERENCES

Prof. Daniel Treisman (chair of the Ph.D. dissertation committee), Department of Political Science, UCLA, 4289 Bunche Hall, Los Angeles, CA 90095, [treisman@polisci.ucla.edu](treisman@polisci.ucla.edu)

Prof. Chad Hazlett (chair of the M.Sc. dissertation committee), Department of Statistics, UCLA, 8105G Mathematical Sciences, Los Angeles, CA 90095, [chazlett@ucla.edu](chazlett@ucla.edu)

Prof. Konstantin Sonin (chair of the M.A. dissertation committee), Harris Public Policy School, University of Chicago, 1155 E60 St, Chicago, IL 60637, [ksonin@uchicago.edu](ksonin@uchicago.edu)
-->


